"""empty message

Revision ID: 172af5c3da3a
Revises: 6ffa345620ca
Create Date: 2022-10-30 17:22:24.690150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172af5c3da3a'
down_revision = '6ffa345620ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
