"""empty message

Revision ID: 76f313e7a8c9
Revises: 214d3f60466f
Create Date: 2022-11-02 04:43:03.074410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f313e7a8c9'
down_revision = '214d3f60466f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("email", 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
